###
get http://localhost:3000/

###
get http://localhost:3000/1

###
post http://localhost:3000/
Content-Type: application/json

{
  "author": "Baz",
  "message": "This is a message added via POST"
}

###
post http://localhost:3000/
Content-Type: application/json

{
  "author": "Person 2",
  "message": "This is another message added via POST"
}

###
put http://localhost:3000/6
Content-Type: application/json

{
  "message": "This was edited via PUT"
}

###
put http://localhost:3000/6
Content-Type: application/json

{
  "message": "This was edited again via PUT"
}

###
delete http://localhost:3000/6